# This is a basic workflow to help you get started with Actions

name: File Remover

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          rm *.webm
          rm *.mov
          
      - name: Commit
        run: |
          git config --global user.name 'Automation Bot'
          git config --global user.email 'BenDev9@users.noreply.github.com'
          
          if ! git diff-files --quiet --ignore-submodules --
          then
              git commit -am "Automated Commit - Updated dictionary"
              git push
          else
              echo Already up to date
          fi
